In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train = pd.read_csv('train.csv')
train.head()

date_time  deg_C  relative_humidity  absolute_humidity  sensor_1  \
0  2010-03-10 18:00:00   13.1               46.0             0.7578    1387.2   
1  2010-03-10 19:00:00   13.2               45.3             0.7255    1279.1   
2  2010-03-10 20:00:00   12.6               56.2             0.7502    1331.9   
3  2010-03-10 21:00:00   11.0               62.4             0.7867    1321.0   
4  2010-03-10 22:00:00   11.9               59.0             0.7888    1272.0   

   sensor_2  sensor_3  sensor_4  sensor_5  target_carbon_monoxide  \
0    1087.8    1056.0    1742.8    1293.4                     2.5   
1     888.2    1197.5    1449.9    1010.9                     2.1   
2     929.6    1060.2    1586.1    1117.0                     2.2   
3     929.0    1102.9    1536.5    1263.2                     2.2   
4     852.7    1180.9    1415.5    1132.2                     1.5   

   target_benzene  target_nitrogen_oxides  
0            12.0                   167.7  
1             9.9                    98.9  
2             9.2                   127.1  
3             9.7                   177.2  
4             6.4                   121.8

In [3]:
train.shape

(7111, 12)

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7111 entries, 0 to 7110
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   date_time               7111 non-null   object 
 1   deg_C                   7111 non-null   float64
 2   relative_humidity       7111 non-null   float64
 3   absolute_humidity       7111 non-null   float64
 4   sensor_1                7111 non-null   float64
 5   sensor_2                7111 non-null   float64
 6   sensor_3                7111 non-null   float64
 7   sensor_4                7111 non-null   float64
 8   sensor_5                7111 non-null   float64
 9   target_carbon_monoxide  7111 non-null   float64
 10  target_benzene          7111 non-null   float64
 11  target_nitrogen_oxides  7111 non-null   float64
dtypes: float64(11), object(1)
memory usage: 666.8+ KB


In [5]:
test = pd.read_csv("test.csv")
test

date_time  deg_C  relative_humidity  absolute_humidity  \
0     2011-01-01 00:00:00    8.0               41.3             0.4375   
1     2011-01-01 01:00:00    5.1               51.7             0.4564   
2     2011-01-01 02:00:00    5.8               51.5             0.4689   
3     2011-01-01 03:00:00    5.0               52.3             0.4693   
4     2011-01-01 04:00:00    4.5               57.5             0.4650   
...                   ...    ...                ...                ...   
2242  2011-04-04 10:00:00   23.2               28.7             0.7568   
2243  2011-04-04 11:00:00   24.5               22.5             0.7119   
2244  2011-04-04 12:00:00   26.6               19.0             0.6406   
2245  2011-04-04 13:00:00   29.1               12.7             0.5139   
2246  2011-04-04 14:00:00   27.9               13.5             0.5028   

      sensor_1  sensor_2  sensor_3  sensor_4  sensor_5  
0       1108.8     745.7     797.1     880.0    1273.1  
1       1249.5     864.9     687.9     972.8    1714.0  
2       1102.6     878.0     693.7     941.9    1300.8  
3       1139.7     916.2     725.6    1011.0    1283.0  
4       1022.4     838.5     871.5     967.0    1142.3  
...        ...       ...       ...       ...       ...  
2242    1340.3    1023.9     522.8    1374.0    1659.8  
2243    1232.8     955.1     616.1    1226.1    1269.0  
2244    1187.7    1052.4     572.8    1253.4    1081.1  
2245    1053.2    1009.0     702.0    1009.8     808.5  
2246    1124.6    1078.4     608.2    1061.3     816.0  

[2247 rows x 9 columns]

In [6]:
submission =pd.read_csv("sample_submission.csv")
submission

date_time  target_carbon_monoxide  target_benzene  \
0     2011-01-01 00:00:00                     2.0            10.0   
1     2011-01-01 01:00:00                     2.0            10.0   
2     2011-01-01 02:00:00                     2.0            10.0   
3     2011-01-01 03:00:00                     2.0            10.0   
4     2011-01-01 04:00:00                     2.0            10.0   
...                   ...                     ...             ...   
2242  2011-04-04 10:00:00                     2.0            10.0   
2243  2011-04-04 11:00:00                     2.0            10.0   
2244  2011-04-04 12:00:00                     2.0            10.0   
2245  2011-04-04 13:00:00                     2.0            10.0   
2246  2011-04-04 14:00:00                     2.0            10.0   

      target_nitrogen_oxides  
0                      300.0  
1                      300.0  
2                      300.0  
3                      300.0  
4                      300.0  
...                      ...  
2242                   300.0  
2243                   300.0  
2244                   300.0  
2245                   300.0  
2246                   300.0  

[2247 rows x 4 columns]

In [7]:
#Define target and drop from train
target = train[['target_carbon_monoxide', 'target_benzene', 'target_nitrogen_oxides']]
train.drop(['target_carbon_monoxide', 'target_benzene', 'target_nitrogen_oxides'], axis = 1,inplace = True)
train

date_time  deg_C  relative_humidity  absolute_humidity  \
0     2010-03-10 18:00:00   13.1               46.0             0.7578   
1     2010-03-10 19:00:00   13.2               45.3             0.7255   
2     2010-03-10 20:00:00   12.6               56.2             0.7502   
3     2010-03-10 21:00:00   11.0               62.4             0.7867   
4     2010-03-10 22:00:00   11.9               59.0             0.7888   
...                   ...    ...                ...                ...   
7106  2010-12-31 20:00:00    9.2               32.0             0.3871   
7107  2010-12-31 21:00:00    9.1               33.2             0.3766   
7108  2010-12-31 22:00:00    9.6               34.6             0.4310   
7109  2010-12-31 23:00:00    8.0               40.7             0.4085   
7110  2011-01-01 00:00:00    8.0               41.3             0.4375   

      sensor_1  sensor_2  sensor_3  sensor_4  sensor_5  
0       1387.2    1087.8    1056.0    1742.8    1293.4  
1       1279.1     888.2    1197.5    1449.9    1010.9  
2       1331.9     929.6    1060.2    1586.1    1117.0  
3       1321.0     929.0    1102.9    1536.5    1263.2  
4       1272.0     852.7    1180.9    1415.5    1132.2  
...        ...       ...       ...       ...       ...  
7106    1000.5     811.2     873.0     909.0     910.5  
7107    1022.7     790.0     951.6     912.9     903.4  
7108    1044.4     767.3     861.9     889.2    1159.1  
7109     952.8     691.9     908.5     917.0    1206.3  
7110    1108.8     745.7     797.1     880.0    1273.1  

[7111 rows x 9 columns]

In [8]:
#Combine train and test
combi = train.append(test)
combi

date_time  deg_C  relative_humidity  absolute_humidity  \
0     2010-03-10 18:00:00   13.1               46.0             0.7578   
1     2010-03-10 19:00:00   13.2               45.3             0.7255   
2     2010-03-10 20:00:00   12.6               56.2             0.7502   
3     2010-03-10 21:00:00   11.0               62.4             0.7867   
4     2010-03-10 22:00:00   11.9               59.0             0.7888   
...                   ...    ...                ...                ...   
2242  2011-04-04 10:00:00   23.2               28.7             0.7568   
2243  2011-04-04 11:00:00   24.5               22.5             0.7119   
2244  2011-04-04 12:00:00   26.6               19.0             0.6406   
2245  2011-04-04 13:00:00   29.1               12.7             0.5139   
2246  2011-04-04 14:00:00   27.9               13.5             0.5028   

      sensor_1  sensor_2  sensor_3  sensor_4  sensor_5  
0       1387.2    1087.8    1056.0    1742.8    1293.4  
1       1279.1     888.2    1197.5    1449.9    1010.9  
2       1331.9     929.6    1060.2    1586.1    1117.0  
3       1321.0     929.0    1102.9    1536.5    1263.2  
4       1272.0     852.7    1180.9    1415.5    1132.2  
...        ...       ...       ...       ...       ...  
2242    1340.3    1023.9     522.8    1374.0    1659.8  
2243    1232.8     955.1     616.1    1226.1    1269.0  
2244    1187.7    1052.4     572.8    1253.4    1081.1  
2245    1053.2    1009.0     702.0    1009.8     808.5  
2246    1124.6    1078.4     608.2    1061.3     816.0  

[9358 rows x 9 columns]

In [9]:
#Drop date_time
combi.drop(['date_time'], axis = 1, inplace = True)
combi

deg_C  relative_humidity  absolute_humidity  sensor_1  sensor_2  \
0      13.1               46.0             0.7578    1387.2    1087.8   
1      13.2               45.3             0.7255    1279.1     888.2   
2      12.6               56.2             0.7502    1331.9     929.6   
3      11.0               62.4             0.7867    1321.0     929.0   
4      11.9               59.0             0.7888    1272.0     852.7   
...     ...                ...                ...       ...       ...   
2242   23.2               28.7             0.7568    1340.3    1023.9   
2243   24.5               22.5             0.7119    1232.8     955.1   
2244   26.6               19.0             0.6406    1187.7    1052.4   
2245   29.1               12.7             0.5139    1053.2    1009.0   
2246   27.9               13.5             0.5028    1124.6    1078.4   

      sensor_3  sensor_4  sensor_5  
0       1056.0    1742.8    1293.4  
1       1197.5    1449.9    1010.9  
2       1060.2    1586.1    1117.0  
3       1102.9    1536.5    1263.2  
4       1180.9    1415.5    1132.2  
...        ...       ...       ...  
2242     522.8    1374.0    1659.8  
2243     616.1    1226.1    1269.0  
2244     572.8    1253.4    1081.1  
2245     702.0    1009.8     808.5  
2246     608.2    1061.3     816.0  

[9358 rows x 8 columns]

In [10]:
#Check for null values
combi.isnull().sum()

deg_C                0
relative_humidity    0
absolute_humidity    0
sensor_1             0
sensor_2             0
sensor_3             0
sensor_4             0
sensor_5             0
dtype: int64

In [11]:
#Normalise combi
combi = (combi.max() - combi) / (combi.max() - combi.min())
combi

deg_C  relative_humidity  absolute_humidity  sensor_1  sensor_2  \
0     0.688935           0.547009           0.719934  0.477589  0.624127   
1     0.686848           0.555556           0.735718  0.551226  0.726675   
2     0.699374           0.422466           0.723648  0.515259  0.705405   
3     0.732777           0.346764           0.705810  0.522684  0.705713   
4     0.713987           0.388278           0.704784  0.556063  0.744914   
...        ...                ...                ...       ...       ...   
2242  0.478079           0.758242           0.720422  0.509537  0.656956   
2243  0.450939           0.833944           0.742364  0.582766  0.692304   
2244  0.407098           0.876679           0.777208  0.613488  0.642314   
2245  0.354906           0.953602           0.839124  0.705109  0.664612   
2246  0.379958           0.943834           0.844549  0.656471  0.628956   

      sensor_3  sensor_4  sensor_5  
0     0.669709  0.489876  0.547689  
1     0.607010  0.612408  0.666597  
2     0.667848  0.555430  0.621938  
3     0.648928  0.576180  0.560401  
4     0.614365  0.626799  0.615540  
...        ...       ...       ...  
2242  0.905973  0.644160  0.393467  
2243  0.864631  0.706032  0.557959  
2244  0.883818  0.694612  0.637049  
2245  0.826569  0.796519  0.751789  
2246  0.868132  0.774975  0.748632  

[9358 rows x 8 columns]

In [12]:
#Split X for training and validationg
y = target
X = combi[: len(train)]
X_test = combi[len(train) :]

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.10, random_state=1)
X_train.shape, y_train.shape, X_val.shape, y_val.shape, X_test.shape

((6399, 8), (6399, 3), (712, 8), (712, 3), (2247, 8))

In [14]:
#Define model
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(X_train,y_train)
r2_score = reg.score(X_train,y_train)
print("Accuracy :- ",r2_score*100,'%')

Accuracy :-  81.79440499888787 %


In [15]:
#Accuracy of validation sets
reg.fit(X_val,y_val)
r_score = reg.score(X_val,y_val)
print("Accuracy :- ",r_score*100,'%')

Accuracy :-  82.99869768110666 %


In [16]:
pred1=reg.predict(X_val)
pred1

array([[  1.73950517,  -1.3472583 , 251.55867254],
       [  0.81009035,   3.76508404,  67.53479242],
       [  1.88393497,  11.52820724,  94.28467424],
       ...,
       [  3.37043928,  17.8991389 , 305.80690733],
       [  1.01367522,   4.2449171 ,  -9.8649728 ],
       [  0.75810132,   5.04978615, -18.75975375]])

In [17]:
pred=reg.predict(X_test)
pred

array([[  1.86000007,   5.38507897, 356.87860794],
       [  2.78529567,   9.59667789, 504.78632936],
       [  2.25423938,   8.27016637, 428.31559936],
       ...,
       [  2.74328782,  12.16138359, 323.91103004],
       [  2.43504934,  10.17794024, 333.3696652 ],
       [  2.72016361,  11.72692283, 354.96604642]])

In [18]:
submission.target_carbon_monoxide = pred[:, 0]
submission.target_benzene = pred[:, 1]
submission.target_nitrogen_oxides = pred[:, 2]
submission.to_csv('submission1.csv', index=False)
submission = pd.read_csv("submission1.csv")
submission

date_time  target_carbon_monoxide  target_benzene  \
0     2011-01-01 00:00:00                1.860000        5.385079   
1     2011-01-01 01:00:00                2.785296        9.596678   
2     2011-01-01 02:00:00                2.254239        8.270166   
3     2011-01-01 03:00:00                2.441715        9.377191   
4     2011-01-01 04:00:00                2.022846        7.342233   
...                   ...                     ...             ...   
2242  2011-04-04 10:00:00                3.205014       13.550733   
2243  2011-04-04 11:00:00                2.614629       10.623772   
2244  2011-04-04 12:00:00                2.743288       12.161384   
2245  2011-04-04 13:00:00                2.435049       10.177940   
2246  2011-04-04 14:00:00                2.720164       11.726923   

      target_nitrogen_oxides  
0                 356.878608  
1                 504.786329  
2                 428.315599  
3                 426.232552  
4                 380.589381  
...                      ...  
2242              400.223120  
2243              327.511254  
2244              323.911030  
2245              333.369665  
2246              354.966046  

[2247 rows x 4 columns]

# ---------------------------------------------------------------------------------------------------------------
#regressor Chain

In [19]:
from sklearn.multioutput import RegressorChain
from sklearn.neural_network import MLPRegressor
model = RegressorChain(MLPRegressor(random_state=1, max_iter = 500)).fit(X_train, y_train)
Accuracy=model.score(X_train, y_train)
print("Accuracy :- ",Accuracy*100,"%")

Accuracy :-  86.60689905605923 %


C:\Users\2000139\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [20]:
#Predict on validation set
#y_pred = model.predict(X_val)
Accuracy1=model.score(X_val, y_val)
print("Accuracy :- ",Accuracy1*100,"%")

Accuracy :-  87.15165752602462 %


In [21]:
#Predict on test set
predictions = model.predict(X_test)
predictions

array([[  1.8050511 ,   5.63337003, 312.07624744],
       [  2.49674216,   8.91879006, 467.70224678],
       [  2.22040471,   8.25109514, 400.28284   ],
       ...,
       [  2.79520324,  13.15396631, 303.8582516 ],
       [  2.25805108,  11.09622106, 294.97631454],
       [  2.66907302,  12.92470447, 316.04894997]])

In [22]:
predictions[predictions < 0] = 0

In [23]:
#Prepare submission
submission.target_carbon_monoxide = predictions[:, 0]
submission.target_benzene = predictions[:, 1]
submission.target_nitrogen_oxides = predictions[:, 2]
submission.to_csv('submission.csv', index=False)
submission = pd.read_csv("submission.csv")
submission

date_time  target_carbon_monoxide  target_benzene  \
0     2011-01-01 00:00:00                1.805051        5.633370   
1     2011-01-01 01:00:00                2.496742        8.918790   
2     2011-01-01 02:00:00                2.220405        8.251095   
3     2011-01-01 03:00:00                2.385047        9.018829   
4     2011-01-01 04:00:00                1.771881        6.721334   
...                   ...                     ...             ...   
2242  2011-04-04 10:00:00                3.154327       14.126370   
2243  2011-04-04 11:00:00                2.520172       11.145159   
2244  2011-04-04 12:00:00                2.795203       13.153966   
2245  2011-04-04 13:00:00                2.258051       11.096221   
2246  2011-04-04 14:00:00                2.669073       12.924704   

      target_nitrogen_oxides  
0                 312.076247  
1                 467.702247  
2                 400.282840  
3                 395.758616  
4                 322.450063  
...                      ...  
2242              383.565909  
2243              301.066413  
2244              303.858252  
2245              294.976315  
2246              316.048950  

[2247 rows x 4 columns]

# -------------------------------------------------------------------------------------------------------------
#random forest Regressor

In [24]:
#Split X for training and validationg
y = target
X = combi[ : len(train)]
X_test = combi[len(train) :]

In [25]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.25, random_state=42)
X_train.shape, y_train.shape, X_val.shape, y_val.shape, X_test.shape

((5333, 8), (5333, 3), (1778, 8), (1778, 3), (2247, 8))

In [26]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(X_train,y_train);
Acc=rf.score(X_train,y_train)
print("Accuracy :-",Acc*100,"%")

Accuracy :- 98.71546522883192 %


In [27]:
#prediction on validation set
prediction = rf.predict(X_val)
# Calculate the absolute errors
errors = abs(prediction - y_val)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')
prediction

Mean Absolute Error: target_carbon_monoxide     0.31
target_benzene             0.93
target_nitrogen_oxides    45.07
dtype: float64 degrees.


array([[  1.3647,   7.6119,  77.0314],
       [  2.2902,  13.2007, 139.8702],
       [  0.9161,   2.9868, 137.9728],
       ...,
       [  0.6691,   3.8993,  48.7488],
       [  1.1749,   6.2246,  72.7853],
       [  1.0824,   6.3144,  48.4004]])

In [28]:
# Use the forest's predict method on the test data
pred1 = rf.predict(X_test)
pred1

array([[  1.4538,   4.9775, 216.7075],
       [  2.0317,   8.5105, 312.1486],
       [  1.8384,   8.2782, 322.4716],
       ...,
       [  3.0325,  14.8868, 384.1242],
       [  2.0871,   8.1426, 303.0138],
       [  2.2675,   9.402 , 312.8642]])

In [29]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_val)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: target_carbon_monoxide    81.91
target_benzene            89.48
target_nitrogen_oxides    71.86
dtype: float64 %.


In [30]:
#Prepare submission
submission.target_carbon_monoxide = pred1[:, 0]
submission.target_benzene = pred1[:, 1]
submission.target_nitrogen_oxides = pred1[:, 2]
submission.to_csv('submission.csv', index=False)
submission = pd.read_csv("submission.csv")
submission

date_time  target_carbon_monoxide  target_benzene  \
0     2011-01-01 00:00:00                  1.4538          4.9775   
1     2011-01-01 01:00:00                  2.0317          8.5105   
2     2011-01-01 02:00:00                  1.8384          8.2782   
3     2011-01-01 03:00:00                  2.0652          8.7128   
4     2011-01-01 04:00:00                  1.3453          6.7109   
...                   ...                     ...             ...   
2242  2011-04-04 10:00:00                  3.9124         19.7911   
2243  2011-04-04 11:00:00                  2.4753         11.7051   
2244  2011-04-04 12:00:00                  3.0325         14.8868   
2245  2011-04-04 13:00:00                  2.0871          8.1426   
2246  2011-04-04 14:00:00                  2.2675          9.4020   

      target_nitrogen_oxides  
0                   216.7075  
1                   312.1486  
2                   322.4716  
3                   342.4750  
4                   271.6216  
...                      ...  
2242                581.5469  
2243                351.1301  
2244                384.1242  
2245                303.0138  
2246                312.8642  

[2247 rows x 4 columns]