In [1]:
# numpy , pandas , matplotlib, seaborn, plotly, cuffinks
import numpy as np 
np.array([4,5,6])

array([4, 5, 6])

In [5]:
# vectoers(one d array) , arrays ,matrices (two d array), num generation
list1=[20,25,75,85]
arr_list1=np.array(list1)
list1

[20, 25, 75, 85]

In [4]:
type(arr_list1)

numpy.ndarray

In [6]:
arr_list1

array([20, 25, 75, 85])

In [8]:
list2=[[10,20,30],[40,50,60],[70,80,90]]
arr_list2=np.array(list2)
arr_list2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
list(range(5,20,2))

[5, 7, 9, 11, 13, 15, 17, 19]

In [10]:
tuple(range(5,20,2))

(5, 7, 9, 11, 13, 15, 17, 19)

In [12]:
arr1=np.arange(5,20,2)
arr1

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [18]:
np.zeros(10)*5

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [20]:
#linspace  =- Lineraly spaced elements
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
np.linspace(100,200,11)

array([100., 110., 120., 130., 140., 150., 160., 170., 180., 190., 200.])

In [23]:
#identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
#random Numbers with numpy(standard and normal distributions )
np.random.rand(5)

array([0.12144789, 0.40755869, 0.84556303, 0.78554161, 0.44148509])

In [29]:
np.random.randn(5)

array([-1.57424989, -0.16715343, -1.25051573, -0.17157396, -0.40866152])

In [32]:
np.random.randint(5)

2

In [31]:
np.random.randint(5)

1

In [33]:
np.random.randint(5,500,100)

array([404, 410, 192, 165, 400, 193,  44,  26,  42, 249, 466, 318,  20,
       381, 183, 463, 260,   8,  31, 347, 203,  41, 144, 345, 348,  42,
       485, 150, 293, 235,  15, 163,  24,  25, 366, 307, 428, 337, 138,
       440, 499, 135, 419, 432, 467, 133, 355, 298, 477,  60, 412, 176,
       497,  62, 224, 164, 297, 475, 160, 350, 107, 173, 472, 117, 225,
        21, 446, 204,  10, 393, 209, 352, 226, 489, 272, 300, 467, 469,
       383,  87, 317, 193, 396, 449, 270, 249,  96, 454, 464, 399, 177,
       197, 396,   7, 353, 351, 471,  19, 283, 492])

In [36]:
arr1=np.arange(25)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr2=arr1.reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
arr2=arr1.reshape(1,25)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])