In [1]:
import numpy as np

In [2]:
np.random.rand(5)

array([0.46313584, 0.65776325, 0.47616109, 0.2536911 , 0.00084762])

In [3]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
ranarr=np.random.randint(0,50,10)
ranarr

array([22, 25, 15, 22, 49, 44, 47, 46, 38, 23])

In [5]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
ranarr.max()

49

In [7]:
ranarr.min()

15

In [8]:
np.max(ranarr)

49

In [9]:
ranarr.argmax()

4

In [10]:
ranarr.argmin()

2

In [11]:
arr1=np.arange(0,11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr1[7]

7

In [13]:
arr1[2:6]

array([2, 3, 4, 5])

In [14]:
#brodcasting
arr2=arr1[3:7]
arr2

array([3, 4, 5, 6])

In [15]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr2[1:3]=78

In [17]:
arr2

array([ 3, 78, 78,  6])

In [18]:
arr1                 #it affecting original array 

array([ 0,  1,  2,  3, 78, 78,  6,  7,  8,  9, 10])

In [19]:
arr1_copy=arr1.copy()
arr1_copy

array([ 0,  1,  2,  3, 78, 78,  6,  7,  8,  9, 10])

In [20]:
#indexing of 2d array
arr2d=np.array(([10,20,30],[40,50,60],[70,80,90]))
arr2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [21]:
arr2d[0]

array([10, 20, 30])

In [22]:
arr2d[0][1]

20

In [23]:
arr2d[1]

array([40, 50, 60])

In [24]:
arr2d[1,0:3]

array([40, 50, 60])

In [25]:
arr2d[1:2,0:3]

array([[40, 50, 60]])

In [26]:
arr2d[1:2,:]

array([[40, 50, 60]])

In [27]:
arr2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [28]:
arr2d[:,1]

array([20, 50, 80])

In [29]:
arr2d[:,1:2]

array([[20],
       [50],
       [80]])

In [30]:
#fancy indexing 

In [31]:
arr2=np.zeros((10,10))
arr2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
lenght=arr2.shape[1]
lenght

10

In [33]:
for a in range(0,lenght):
    arr2[a]=a
arr2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [34]:
arr2[[1,4,6,8]]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [35]:
#selection
arr1=np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr1>0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [37]:
arr1>8

array([False, False, False, False, False, False, False, False,  True,
        True])

In [38]:
arr1[arr1>8]

array([ 9, 10])

In [39]:
#operations

In [40]:
arr3=np.arange(0,11)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr3+arr3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [42]:
arr3-arr3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
arr3*arr3

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [44]:
arr3/arr3

C:\Users\2000139\AppData\Local\Temp\ipykernel_14424\3844900078.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr3/arr3


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [45]:
1/arr3

C:\Users\2000139\AppData\Local\Temp\ipykernel_14424\1374327335.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr3


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [46]:
np.log(arr3)

C:\Users\2000139\AppData\Local\Temp\ipykernel_14424\2430430252.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr3)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [47]:
np.exp(arr3)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [48]:
np.max(arr3)

10

# Pandas

In [49]:
#series/dataframe/missing data/grouping/contactening/operations /ip and op data.

In [50]:
#series
import pandas as pd

In [51]:
list1=['abc','def','ghi']
list1

['abc', 'def', 'ghi']

In [52]:
list2=[200,300,400]
list2

[200, 300, 400]

In [53]:
arr=np.array([500,700,900])
arr

array([500, 700, 900])

In [54]:
d={'x':1000,'y':2000,'z':3000}
d

{'x': 1000, 'y': 2000, 'z': 3000}

In [55]:
pd.Series(list1)

0    abc
1    def
2    ghi
dtype: object

In [56]:
type(pd.Series(list1))

pandas.core.series.Series

In [57]:
pd.Series(data=list1)

0    abc
1    def
2    ghi
dtype: object

In [58]:
pd.Series(data=list1,index=list2)

200    abc
300    def
400    ghi
dtype: object

In [59]:
pd.Series(data=list2,index=list1)

abc    200
def    300
ghi    400
dtype: int64

In [60]:
pd.Series(data=list1,index=arr)

500    abc
700    def
900    ghi
dtype: object

In [61]:
pd.Series(d)

x    1000
y    2000
z    3000
dtype: int64

In [62]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [63]:
#indexing
ser1=pd.Series([1,2,3,4],index=['USA','Germany','USSR','Japan'])
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [64]:
ser2=pd.Series([1,2,3,4],index=['USA','Germany','Italy','Japan'])
ser2

USA        1
Germany    2
Italy      3
Japan      4
dtype: int64

In [65]:
ser1+ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [66]:
#Dataframe

In [67]:
n=np.random.randn(5,4)
n

array([[ 2.43485304, -0.00820157, -0.69918005,  1.07506557],
       [-0.12639143, -0.0600441 , -1.43089236, -0.07079091],
       [-0.89920285, -0.89109083, -0.06226228, -1.81818969],
       [ 0.87936461, -0.0444458 , -0.50429808, -0.84721448],
       [-0.519298  , -0.75759607, -0.88235891,  2.96999073]])

In [68]:
df=pd.DataFrame(data=n)
df

0         1         2         3
0  2.434853 -0.008202 -0.699180  1.075066
1 -0.126391 -0.060044 -1.430892 -0.070791
2 -0.899203 -0.891091 -0.062262 -1.818190
3  0.879365 -0.044446 -0.504298 -0.847214
4 -0.519298 -0.757596 -0.882359  2.969991

In [69]:
"A B C D E".split()

['A', 'B', 'C', 'D', 'E']

In [70]:
df1=pd.DataFrame(data=n,index="A B C D E".split(),columns="W X Y Z".split())
df1

W         X         Y         Z
A  2.434853 -0.008202 -0.699180  1.075066
B -0.126391 -0.060044 -1.430892 -0.070791
C -0.899203 -0.891091 -0.062262 -1.818190
D  0.879365 -0.044446 -0.504298 -0.847214
E -0.519298 -0.757596 -0.882359  2.969991

In [71]:
df1['Y']

A   -0.699180
B   -1.430892
C   -0.062262
D   -0.504298
E   -0.882359
Name: Y, dtype: float64

In [72]:
type(df1['Y'])

pandas.core.series.Series

In [73]:
df1[['W','Y']]

W         Y
A  2.434853 -0.699180
B -0.126391 -1.430892
C -0.899203 -0.062262
D  0.879365 -0.504298
E -0.519298 -0.882359

In [74]:
type(df1[['W','Y']])

pandas.core.frame.DataFrame

In [75]:
df1

W         X         Y         Z
A  2.434853 -0.008202 -0.699180  1.075066
B -0.126391 -0.060044 -1.430892 -0.070791
C -0.899203 -0.891091 -0.062262 -1.818190
D  0.879365 -0.044446 -0.504298 -0.847214
E -0.519298 -0.757596 -0.882359  2.969991

In [76]:
df1['Thursday']=df1['Y']+df1['X']
df1

W         X         Y         Z  Thursday
A  2.434853 -0.008202 -0.699180  1.075066 -0.707382
B -0.126391 -0.060044 -1.430892 -0.070791 -1.490936
C -0.899203 -0.891091 -0.062262 -1.818190 -0.953353
D  0.879365 -0.044446 -0.504298 -0.847214 -0.548744
E -0.519298 -0.757596 -0.882359  2.969991 -1.639955

In [77]:
df1.drop('Thursday',axis=1)

W         X         Y         Z
A  2.434853 -0.008202 -0.699180  1.075066
B -0.126391 -0.060044 -1.430892 -0.070791
C -0.899203 -0.891091 -0.062262 -1.818190
D  0.879365 -0.044446 -0.504298 -0.847214
E -0.519298 -0.757596 -0.882359  2.969991

In [78]:
df1

W         X         Y         Z  Thursday
A  2.434853 -0.008202 -0.699180  1.075066 -0.707382
B -0.126391 -0.060044 -1.430892 -0.070791 -1.490936
C -0.899203 -0.891091 -0.062262 -1.818190 -0.953353
D  0.879365 -0.044446 -0.504298 -0.847214 -0.548744
E -0.519298 -0.757596 -0.882359  2.969991 -1.639955

In [79]:
df1.drop('Thursday',axis=1,inplace=True)
df1

W         X         Y         Z
A  2.434853 -0.008202 -0.699180  1.075066
B -0.126391 -0.060044 -1.430892 -0.070791
C -0.899203 -0.891091 -0.062262 -1.818190
D  0.879365 -0.044446 -0.504298 -0.847214
E -0.519298 -0.757596 -0.882359  2.969991

In [80]:
df1.drop('D',axis=0)

W         X         Y         Z
A  2.434853 -0.008202 -0.699180  1.075066
B -0.126391 -0.060044 -1.430892 -0.070791
C -0.899203 -0.891091 -0.062262 -1.818190
E -0.519298 -0.757596 -0.882359  2.969991

In [81]:
df1

W         X         Y         Z
A  2.434853 -0.008202 -0.699180  1.075066
B -0.126391 -0.060044 -1.430892 -0.070791
C -0.899203 -0.891091 -0.062262 -1.818190
D  0.879365 -0.044446 -0.504298 -0.847214
E -0.519298 -0.757596 -0.882359  2.969991